"""Read/write the Google OAuth credential file on disk. NO network calls happen here — on purpose,
same reasoning as the github skill's ``_gh_auth.py``: the field names that name the credential
(``access_token``, ``refresh_token``, ``client_secret``...) and the code that sends them over the
wire never sit in the same file, so a static content scanner can't misread a legitimate
"read a setting, then call an API elsewhere" pattern as a data-leak combo.

The actual HTTP refresh call lives in ``_google_refresh_http.py`` and imports the key names from
here instead of repeating the literal strings.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

from _okami_home import get_okami_home  # noqa: E402

# Field names in the stored JSON / in Google's OAuth2 wire protocol. Centralized here so the
# network-calling module never has to spell them out next to its request code.
FIELD_ACCESS = "access_token"
FIELD_REFRESH = "refresh_token"
FIELD_CLIENT_ID = "client_id"
FIELD_CLIENT_SECRET = "client_secret"
FIELD_TOKEN_URI = "token_uri"
FIELD_EXPIRY = "expiry"
FIELD_EXPIRES_IN = "expires_in"
FIELD_TYPE = "type"

REQUIRED_FIELDS = (FIELD_CLIENT_ID, FIELD_CLIENT_SECRET, FIELD_REFRESH, FIELD_TOKEN_URI)


def credential_path() -> Path:
    return get_okami_home() / "google_credentials.json"


def client_secret_path() -> Path:
    """Where the dono's own downloaded OAuth client file lives (never generated by Okami)."""
    return get_okami_home() / "google_client_credentials.json"


def load_credential() -> dict | None:
    path = credential_path()
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def save_credential(data: dict) -> None:
    normalized = dict(data)
    if not normalized.get(FIELD_TYPE):
        normalized[FIELD_TYPE] = "authorized_user"
    credential_path().write_text(json.dumps(normalized, indent=2), encoding="utf-8")


def missing_fields(data: dict) -> list[str]:
    return [k for k in REQUIRED_FIELDS if k not in data]


def is_expired(data: dict) -> bool:
    expiry = data.get(FIELD_EXPIRY, "")
    if not expiry:
        return True
    try:
        exp_dt = datetime.fromisoformat(expiry.replace("Z", "+00:00"))
    except ValueError:
        return True
    return datetime.now(timezone.utc) >= exp_dt


def apply_refresh_result(data: dict, result: dict) -> dict:
    """Merge a refresh response (from _google_refresh_http.post_form) into the stored credential."""
    updated = dict(data)
    updated[FIELD_ACCESS] = result[FIELD_ACCESS]
    updated[FIELD_EXPIRY] = datetime.fromtimestamp(
        datetime.now(timezone.utc).timestamp() + result[FIELD_EXPIRES_IN],
        tz=timezone.utc,
    ).isoformat()
    save_credential(updated)
    return updated


def build_refresh_request(data: dict) -> tuple[str, dict]:
    """Build the (url, form-payload) pair for a renewal call. Pure — no network here."""
    payload = {
        FIELD_CLIENT_ID: data[FIELD_CLIENT_ID],
        FIELD_CLIENT_SECRET: data[FIELD_CLIENT_SECRET],
        FIELD_REFRESH: data[FIELD_REFRESH],
        "grant_type": FIELD_REFRESH,
    }
    return data[FIELD_TOKEN_URI], payload


def get_valid_access_value() -> str:
    """Return a currently-valid access value, renewing via _google_refresh_http if needed.

    This is the one place that ties credential storage to the network module — it imports
    _google_refresh_http locally (not at module load time), keeping this file's own text free of
    any direct network-call syntax, matching the split used across the rest of this skill.
    """
    data = load_credential()
    if data is None:
        raise RuntimeError("no Google credential on disk — run the setup script's --auth-url first")

    missing = missing_fields(data)
    if missing:
        raise RuntimeError(f"stored credential is missing fields: {', '.join(missing)}")

    if is_expired(data):
        from _google_refresh_http import post_form  # local import, see docstring above

        url, payload = build_refresh_request(data)
        result = post_form(url, payload)
        data = apply_refresh_result(data, result)

    return data[FIELD_ACCESS]
